---
# "This is a sample config file"

# "A trailing / is required when specifying paths"
massive_input_dir:  /scratch/PROJECT_ID/WinSCP/MASSIVE_input/
massive_output_dir: /scratch/PROJECT_ID/WinSCP/MASSIVE_output/

processing_file: processing.j2
processing_output_folders: { rawdata: "rawdata",
                             deskewed_output: "deskewed",
                             deconvolved_output: "deconvolved",
                             photobleach_output: "photoBleachCorrection"}

log-level: logging.DEBUG
log-files:
    watch: /projects/PROJECT_ID/scripts/var/log/watchFolder.log


